version: '2'

services:

  angular-seed:
    build:
      context: .
      dockerfile: ./.docker/angular-seed.production.dockerfile
    command: npm run build.prod
    container_name: angular-seed-build-prod
    image: angular-seed
    networks:
      - prod-network
    volumes:
      - ./dist:/home/app/angular-seed/dist

  angular-seed-nginx:
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/angular-seed.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: angular-seed-nginx-prod
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    image: nginx
    networks:
      - prod-network
    ports:
      - '5555:80'
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/angular-seed.template
      - ./dist/prod:/var/www/dist/prod

networks:
  prod-network:
    driver: bridge
