version: '2'

services:

  web:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_prod
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/angular-seed.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: angular-seed-prod
    image: angular-seed/prod
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - prod-network
    ports:
      - '5555:80'

networks:
  prod-network:
    driver: bridge
